# Turning Data Into Information

* At the heart of the big data revolution
* A very liberal arts thing to do -- Requires problem solving, **and** communication
* Requires more than just a passing skill at querying the database

# Introduce Data Modeling

* Key tool for communication
* Describes the schema of the data -- the type or kinds of data, not the data itself

| City |
|---|
| id |
| name |
| countrycode |
| district |
| population |

| Country |
|---|
| code |
| name |
| continent |
| region |
| surfacearea |
| indepyear |
| population |
| lifeexpectancy |
| gnp |
| gnpold |
| localname |
| governmentform |
| headofstate |
| capital |
| code2 |

# Introduce Data Modeling

* Describes relationships between things

Country **has** City as a capital

City **has** countrycode

# Relational Algebra

## Key Terms

* Relation

* Tuple

  * A single row/record of a relation

* Operators

* Single-relation

  * Project
  * Select
  * Sort
  * Rename
  * Extend
  * Groupby

* Two-relation

  * Product
  * Union
  * Join
  * Semijoin
  * Antijoin
  * Outer join

**The result of applying an operator to a relation is another relation**

[Luther JupyterHub](https://knuth.luther.edu:8443)

# A Relation with Country Data¶

In [2]:
from reframe import Relation
    
country = Relation('/home/faculty/yasiro01/pub/country.csv', sep='|')

`country` is an object of type Relation that holds all the data from the *country.csv* file

In [3]:
country

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381740.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ
5,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,US Territory,George W. Bush,54.0,AS
6,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,NaN,55.0,AD
7,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
8,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
9,ATG,Antigua and Barbuda,North America,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63.0,AG
10,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
11,ARG,Argentina,South America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69.0,AR
12,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotarjan,126.0,AM
13,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
14,AUS,Australia,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,AU
15,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144.0,AZ
16,BHS,Bahamas,North America,Caribbean,13878.0,1973.0,307000,71.1,3527.0,3347.0,The Bahamas,Constitutional Monarchy,Elisabeth II,148.0,BS
17,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149.0,BH
18,BGD,Bangladesh,Asia,Southern and Central Asia,143998.0,1971.0,129155000,60.2,32852.0,31966.0,Bangladesh,Republic,Shahabuddin Ahmad,150.0,BD
19,BRB,Barbados,North America,Caribbean,430.0,1966.0,270000,73.0,2223.0,2186.0,Barbados,Constitutional Monarchy,Elisabeth II,174.0,BB
20,BEL,Belgium,Europe,Western Europe,30518.0,1830.0,10239000,77.8,249704.0,243948.0,België/Belgique,"Constitutional Monarchy, Federation",Albert II,179.0,BE
21,BLZ,Belize,North America,Central America,22696.0,1981.0,241000,70.9,630.0,616.0,Belize,Constitutional Monarchy,Elisabeth II,185.0,BZ
22,BEN,Benin,Africa,Western Africa,112622.0,1960.0,6097000,50.2,2357.0,2141.0,Bénin,Republic,Mathieu Kérékou,187.0,BJ
23,BMU,Bermuda,North America,North America,53.0,NaN,65000,76.9,2328.0,2190.0,Bermuda,Dependent Territory of the UK,Elisabeth II,191.0,BM
24,BTN,Bhutan,Asia,Southern and Central Asia,47000.0,1910.0,2124000,52.4,372.0,383.0,Druk-Yul,Monarchy,Jigme Singye Wangchuk,192.0,BT
25,BOL,Bolivia,South America,South America,1098580.0,1825.0,8329000,63.7,8571.0,7967.0,Bolivia,Republic,Hugo Bánzer Suárez,194.0,BO
26,BIH,Bosnia and Herzegovina,Europe,Southern Europe,51197.0,1992.0,3972000,71.5,2841.0,NaN,Bosna i Hercegovina,Federal Republic,Ante Jelavic,201.0,BA
27,BWA,Botswana,Africa,Southern Africa,581730.0,1966.0,1622000,39.3,4834.0,4935.0,Botswana,Republic,Festus G. Mogae,204.0,BW
28,BRA,Brazil,South America,South America,8547400.0,1822.0,170115000,62.9,776739.0,804108.0,Brasil,Federal Republic,Fernando Henrique Cardoso,211.0,BR
29,GBR,United Kingdom,Europe,British Islands,242900.0,1066.0,59623400,77.7,1378330.0,1296830.0,United Kingdom,Constitutional Monarchy,Elisabeth II,456.0,GB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,TUR,Turkey,Asia,Middle East,774815.0,1923.0,66591000,71.0,210721.0,189122.0,Türkiye,Republic,Ahmet Necdet Sezer,3358.0,TR
210,TKM,Turkmenistan,Asia,Southern and Central Asia,488100.0,1991.0,4459000,60.9,4397.0,2000.0,Türkmenostan,Republic,Saparmurad Nijazov,3419.0,TM
211,TCA,Turks and Caicos Islands,North America,Caribbean,430.0,NaN,17000,73.3,96.0,NaN,The Turks and Caicos Islands,Dependent Territory of the UK,Elisabeth II,3423.0,TC
212,TUV,Tuvalu,Oceania,Polynesia,26.0,1978.0,12000,66.3,6.0,NaN,Tuvalu,Constitutional Monarchy,Elisabeth II,3424.0,TV
213,UGA,Uganda,Africa,Eastern Africa,241038.0,1962.0,21778000,42.9,6313.0,6887.0,Uganda,Republic,Yoweri Museveni,3425.0,UG
214,UKR,Ukraine,Europe,Eastern Europe,603700.0,1991.0,50456000,66.0,42168.0,49677.0,Ukrajina,Republic,Leonid Kutma,3426.0,UA
215,HUN,Hungary,Europe,Eastern Europe,93030.0,1918.0,10043200,71.4,48267.0,45914.0,Magyarország,Republic,Ferenc Mádl,3483.0,HU
216,URY,Uruguay,South America,South America,175016.0,1828.0,3337000,75.2,20831.0,19967.0,Uruguay,Republic,Jorge Batlle Ibáñez,3492.0,UY
217,NCL,New Caledonia,Oceania,Melanesia,18575.0,NaN,214000,72.8,3563.0,NaN,Nouvelle-Calédonie,Nonmetropolitan Territory of France,Jacques Chirac,3493.0,NC
218,NZL,New Zealand,Oceania,Australia and New Zealand,270534.0,1907.0,3862000,77.8,54669.0,64960.0,New Zealand/Aotearoa,Constitutional Monarchy,Elisabeth II,3499.0,NZ
219,UZB,Uzbekistan,Asia,Southern and Central Asia,447400.0,1991.0,24318000,63.7,14194.0,21300.0,Uzbekiston,Republic,Islam Karimov,3503.0,UZ
220,BLR,Belarus,Europe,Eastern Europe,207600.0,1991.0,10236000,68.0,13714.0,NaN,Belarus,Republic,Aljaksandr Lukaenka,3520.0,BY
221,WLF,Wallis and Futuna,Oceania,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF
222,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,VU
223,VAT,Holy See (Vatican City State),Europe,Southern Europe,0.4,1929.0,1000,NaN,9.0,NaN,Santa Sede/Città del Vaticano,Independent Church State,Johannes Paavali II,3538.0,VA
224,VEN,Venezuela,South America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,Venezuela,Federal Republic,Hugo Chávez Frías,3539.0,VE
225,RUS,Russian Federation,Europe,Eastern Europe,17075400.0,1991.0,146934000,67.2,276608.0,442989.0,Rossija,Federal Republic,Vladimir Putin,3580.0,RU
226,VNM,Vietnam,Asia,Southeast Asia,331689.0,1945.0,79832000,69.3,21929.0,22834.0,Viêt Nam,Socialistic Republic,Trân Duc Luong,3770.0,VN
227,EST,Estonia,Europe,Baltic Countries,45227.0,1991.0,1439200,69.5,5328.0,3371.0,Eesti,Republic,Lennart Meri,3791.0,EE
228,USA,United States,North America,North America,9363520.0,1776.0,278357000,77.1,8510700.0,8110900.0,United States,Federal Republic,George W. Bush,3813.0,US
229,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the United States,US Territory,George W. Bush,4067.0,VI
230,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW
231,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
232,ATA,Antarctica,Antarctica,Antarctica,13120000.0,NaN,0,NaN,0.0,NaN,,Co-administrated,NaN,NaN,AQ
233,BVT,Bouvet Island,Antarctica,Antarctica,59.0,NaN,0,NaN,0.0,NaN,Bouvetøya,Dependent Territory of Norway,Harald V,NaN,BV
234,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the UK,Elisabeth II,NaN,IO
235,SGS,South Georgia and the South Sandwich Islands,Antarctica,Antarctica,3903.0,NaN,0,NaN,0.0,NaN,South Georgia and the South Sandwich Islands,Dependent Territory of the UK,Elisabeth II,NaN,GS
236,HMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359.0,NaN,0,NaN,0.0,NaN,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
237,ATF,French Southern territories,Antarctica,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes françaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
238,UMI,United States Minor Outlying Islands,Oceania,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,United States Minor Outlying Islands,Dependent Territory of the US,George W. Bush,NaN,UM

# Relational Algebra: Limit the Output

Operation `head()` limits the output. By default it's 5 tuples, but that number can be changed.

In [4]:
country.head()

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381740.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ

Specify number of tuples to view (default 5)

In [5]:
country.head(1)

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF

Use `tail` to see the last tuples.

In [6]:
country.tail()

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
234,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the UK,Elisabeth II,NaN,IO
235,SGS,South Georgia and the South Sandwich Islands,Antarctica,Antarctica,3903.0,NaN,0,NaN,0.0,NaN,South Georgia and the South Sandwich Islands,Dependent Territory of the UK,Elisabeth II,NaN,GS
236,HMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359.0,NaN,0,NaN,0.0,NaN,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
237,ATF,French Southern territories,Antarctica,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes françaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
238,UMI,United States Minor Outlying Islands,Oceania,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,United States Minor Outlying Islands,Dependent Territory of the US,George W. Bush,NaN,UM

# Relational Algebra: Project

List the fields to display in brackets.

In [9]:
country.project(['continent'])

         continent
0             Asia
1           Europe
2    North America
4           Africa
5          Oceania
11   South America
232     Antarctica

In [5]:
country.project(['name', 'indepyear', 'population']).head()

                   name  indepyear  population
0           Afghanistan     1919.0    22720000
1           Netherlands     1581.0    15864000
2  Netherlands Antilles        NaN      217000
3               Albania     1912.0     3401200
4               Algeria     1962.0    31471000

# Relational Algebra: Query

In [6]:
country.query('indepyear < 1200')

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
29,GBR,United Kingdom,Europe,British Islands,242900.0,1066.0,59623400,77.7,1378330.0,1296830.0,United Kingdom,Constitutional Monarchy,Elisabeth II,456.0,GB
48,ETH,Ethiopia,Africa,Eastern Africa,1104300.0,-1000.0,62565000,45.2,6353.0,6180.0,YeItyop´iya,Republic,Negasso Gidada,756.0,ET
81,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532.0,JP
93,CHN,China,Asia,Eastern Asia,9572900.0,-1523.0,1277558000,71.4,982268.0,917719.0,Zhongquo,People'sRepublic,Jiang Zemin,1891.0,CN
159,PRT,Portugal,Europe,Southern Europe,91982.0,1143.0,9997600,75.8,105954.0,102133.0,Portugal,Republic,Jorge Sampãio,2914.0,PT
164,FRA,France,Europe,Western Europe,551500.0,843.0,59225700,78.8,1424285.0,1392448.0,France,Republic,Jacques Chirac,2974.0,FR
170,SWE,Sweden,Europe,Nordic Countries,449964.0,836.0,8861400,79.6,226492.0,227757.0,Sverige,Constitutional Monarchy,Carl XVI Gustaf,3048.0,SE
180,SMR,San Marino,Europe,Southern Europe,61.0,885.0,27000,81.1,510.0,NaN,San Marino,Republic,NaN,3171.0,SM
200,DNK,Denmark,Europe,Nordic Countries,43094.0,800.0,5330000,76.5,174099.0,169264.0,Danmark,Constitutional Monarchy,Margrethe II,3315.0,DK

In [10]:
country.query("continent == 'Asia'")

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
10,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
12,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotarjan,126.0,AM
15,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144.0,AZ
17,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149.0,BH
18,BGD,Bangladesh,Asia,Southern and Central Asia,143998.0,1971.0,129155000,60.2,32852.0,31966.0,Bangladesh,Republic,Shahabuddin Ahmad,150.0,BD
24,BTN,Bhutan,Asia,Southern and Central Asia,47000.0,1910.0,2124000,52.4,372.0,383.0,Druk-Yul,Monarchy,Jigme Singye Wangchuk,192.0,BT
31,BRN,Brunei,Asia,Southeast Asia,5765.0,1984.0,328000,73.6,11705.0,12460.0,Brunei Darussalam,Monarchy (Sultanate),Haji Hassan al-Bolkiah,538.0,BN
51,PHL,Philippines,Asia,Southeast Asia,300000.0,1946.0,75967000,67.5,65107.0,82239.0,Pilipinas,Republic,Gloria Macapagal-Arroyo,766.0,PH
55,GEO,Georgia,Asia,Middle East,69700.0,1991.0,4968000,64.5,6064.0,5924.0,Sakartvelo,Republic,Eduard evardnadze,905.0,GE
68,HKG,Hong Kong,Asia,Eastern Asia,1075.0,NaN,6782000,79.5,166448.0,173610.0,Xianggang/Hong Kong,Special Administrative Region of China,Jiang Zemin,937.0,HK
70,IDN,Indonesia,Asia,Southeast Asia,1904570.0,1945.0,212107000,68.0,84982.0,215002.0,Indonesia,Republic,Abdurrahman Wahid,939.0,ID
71,IND,India,Asia,Southern and Central Asia,3287260.0,1947.0,1013662000,62.5,447114.0,430572.0,Bharat/India,Federal Republic,Kocheril Raman Narayanan,1109.0,IN
72,IRQ,Iraq,Asia,Middle East,438317.0,1932.0,23115000,66.5,11500.0,NaN,Al-´Iraq,Republic,Saddam Hussein al-Takriti,1365.0,IQ
73,IRN,Iran,Asia,Southern and Central Asia,1648200.0,1906.0,67702000,69.7,195746.0,160151.0,Iran,Islamic Republic,Ali Mohammad Khatami-Ardakani,1380.0,IR
76,ISR,Israel,Asia,Middle East,21056.0,1948.0,6217000,78.6,97477.0,98577.0,Yisrael/Israil,Republic,Moshe Katzav,1450.0,IL
78,TMP,East Timor,Asia,Southeast Asia,14874.0,NaN,885000,46.0,0.0,NaN,Timor Timur,Administrated by the UN,José Alexandre Gusmão,1522.0,TP
81,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532.0,JP
82,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
83,JOR,Jordan,Asia,Middle East,88946.0,1946.0,5083000,77.4,7526.0,7051.0,Al-Urdunn,Constitutional Monarchy,Abdullah II,1786.0,JO
86,KHM,Cambodia,Asia,Southeast Asia,181035.0,1953.0,11168000,56.5,5121.0,5670.0,Kâmpuchéa,Constitutional Monarchy,Norodom Sihanouk,1800.0,KH
90,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
93,CHN,China,Asia,Eastern Asia,9572900.0,-1523.0,1277558000,71.4,982268.0,917719.0,Zhongquo,People'sRepublic,Jiang Zemin,1891.0,CN
94,KGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900.0,1991.0,4699000,63.4,1626.0,1767.0,Kyrgyzstan,Republic,Askar Akajev,2253.0,KG
101,PRK,North Korea,Asia,Eastern Asia,120538.0,1948.0,24039000,70.7,5332.0,NaN,Choson Minjujuui In´min Konghwaguk (Bukhan),Socialistic Republic,Kim Jong-il,2318.0,KP
102,KOR,South Korea,Asia,Eastern Asia,99434.0,1948.0,46844000,74.4,320749.0,442544.0,Taehan Minguk (Namhan),Republic,Kim Dae-jung,2331.0,KR
106,KWT,Kuwait,Asia,Middle East,17818.0,1961.0,1972000,76.1,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW
107,CYP,Cyprus,Asia,Middle East,9251.0,1960.0,754700,76.7,9333.0,8246.0,Kýpros/Kibris,Republic,Glafkos Klerides,2430.0,CY
108,LAO,Laos,Asia,Southeast Asia,236800.0,1953.0,5433000,53.1,1292.0,1746.0,Lao,Republic,Khamtay Siphandone,2432.0,LA
111,LBN,Lebanon,Asia,Middle East,10400.0,1941.0,3282000,71.3,17121.0,15129.0,Lubnan,Republic,Émile Lahoud,2438.0,LB
118,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO
122,MDV,Maldives,Asia,Southern and Central Asia,298.0,1965.0,286000,62.2,199.0,NaN,Dhivehi Raajje/Maldives,Republic,Maumoon Abdul Gayoom,2463.0,MV
123,MYS,Malaysia,Asia,Southeast Asia,329758.0,1957.0,22244000,70.8,69213.0,97884.0,Malaysia,"Constitutional Monarchy, Federation",Salahuddin Abdul Aziz Shah Alhaj,2464.0,MY
136,MNG,Mongolia,Asia,Eastern Asia,1566500.0,1921.0,2662000,67.3,1043.0,933.0,Mongol Uls,Republic,Natsagiin Bagabandi,2696.0,MN
139,MMR,Myanmar,Asia,Southeast Asia,676578.0,1948.0,45611000,54.9,180375.0,171028.0,Myanma Pye,Republic,kenraali Than Shwe,2710.0,MM
142,NPL,Nepal,Asia,Southern and Central Asia,147181.0,1769.0,23930000,57.8,4768.0,4837.0,Nepal,Constitutional Monarchy,Gyanendra Bir Bikram,2729.0,NP
150,OMN,Oman,Asia,Middle East,309500.0,1951.0,2542000,71.8,16904.0,16153.0,´Uman,Monarchy (Sultanate),Qabus ibn Sa´id,2821.0,OM
151,PAK,Pakistan,Asia,Southern and Central Asia,796095.0,1947.0,156483000,61.1,61289.0,58549.0,Pakistan,Republic,Mohammad Rafiq Tarar,2831.0,PK
163,QAT,Qatar,Asia,Middle East,11000.0,1971.0,599000,72.4,9472.0,8920.0,Qatar,Monarchy,Hamad ibn Khalifa al-Thani,2973.0,QA
182,SAU,Saudi Arabia,Asia,Middle East,2149690.0,1932.0,21607000,67.8,137635.0,146171.0,Al-´Arabiya as-Sa´udiya,Monarchy,Fahd ibn Abdul-Aziz al-Sa´ud,3173.0,SA
186,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208.0,SG
190,LKA,Sri Lanka,Asia,Southern and Central Asia,65610.0,1948.0,18827000,71.8,15706.0,15091.0,Sri Lanka/Ilankai,Republic,Chandrika Kumaratunga,3217.0,LK
196,SYR,Syria,Asia,Middle East,185180.0,1941.0,16125000,68.5,65984.0,64926.0,Suriya,Republic,Bashar al-Assad,3250.0,SY
197,TJK,Tajikistan,Asia,Southern and Central Asia,143100.0,1991.0,6188000,64.1,1990.0,1056.0,Toçikiston,Republic,Emomali Rahmonov,3261.0,TJ
198,TWN,Taiwan,Asia,Eastern Asia,36188.0,1945.0,22256000,76.4,256254.0,263451.0,Tai-wan,Republic,Chen Shui-bian,3263.0,TW
201,THA,Thailand,Asia,Southeast Asia,513115.0,1350.0,61399000,68.6,116416.0,153907.0,Prathet Thai,Constitutional Monarchy,Bhumibol Adulyadej,3320.0,TH
209,TUR,Turkey,Asia,Middle East,774815.0,1923.0,66591000,71.0,210721.0,189122.0,Türkiye,Republic,Ahmet Necdet Sezer,3358.0,TR
210,TKM,Turkmenistan,Asia,Southern and Central Asia,488100.0,1991.0,4459000,60.9,4397.0,2000.0,Türkmenostan,Republic,Saparmurad Nijazov,3419.0,TM
219,UZB,Uzbekistan,Asia,Southern and Central Asia,447400.0,1991.0,24318000,63.7,14194.0,21300.0,Uzbekiston,Republic,Islam Karimov,3503.0,UZ
226,VNM,Vietnam,Asia,Southeast Asia,331689.0,1945.0,79832000,69.3,21929.0,22834.0,Viêt Nam,Socialistic Republic,Trân Duc Luong,3770.0,VN
231,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS

# Relational Algebra: Pipes

In [11]:
country.query("indepyear >= 1991").project(['name', 'indepyear', 'region'])

                       name  indepyear                     region
12                  Armenia     1991.0                Middle East
15               Azerbaijan     1991.0                Middle East
26   Bosnia and Herzegovina     1992.0            Southern Europe
45                  Eritrea     1993.0             Eastern Africa
55                  Georgia     1991.0                Middle East
90                Kazakstan     1991.0  Southern and Central Asia
94               Kyrgyzstan     1991.0  Southern and Central Asia
104                 Croatia     1991.0            Southern Europe
109                  Latvia     1991.0           Baltic Countries
115               Lithuania     1991.0           Baltic Countries
120               Macedonia     1991.0            Southern Europe
134                 Moldova     1991.0             Eastern Europe
152                   Palau     1994.0                 Micronesia
187                Slovakia     1993.0             Eastern Europe
188                Slovenia     1991.0            Southern Europe
197              Tajikistan     1991.0  Southern and Central Asia
207          Czech Republic     1993.0             Eastern Europe
210            Turkmenistan     1991.0  Southern and Central Asia
214                 Ukraine     1991.0             Eastern Europe
219              Uzbekistan     1991.0  Southern and Central Asia
220                 Belarus     1991.0             Eastern Europe
225      Russian Federation     1991.0             Eastern Europe
227                 Estonia     1991.0           Baltic Countries

In [12]:
country.query("continent == 'Asia'").query("indepyear >= 1991")

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
12,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotarjan,126.0,AM
15,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144.0,AZ
55,GEO,Georgia,Asia,Middle East,69700.0,1991.0,4968000,64.5,6064.0,5924.0,Sakartvelo,Republic,Eduard evardnadze,905.0,GE
90,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
94,KGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900.0,1991.0,4699000,63.4,1626.0,1767.0,Kyrgyzstan,Republic,Askar Akajev,2253.0,KG
197,TJK,Tajikistan,Asia,Southern and Central Asia,143100.0,1991.0,6188000,64.1,1990.0,1056.0,Toçikiston,Republic,Emomali Rahmonov,3261.0,TJ
210,TKM,Turkmenistan,Asia,Southern and Central Asia,488100.0,1991.0,4459000,60.9,4397.0,2000.0,Türkmenostan,Republic,Saparmurad Nijazov,3419.0,TM
219,UZB,Uzbekistan,Asia,Southern and Central Asia,447400.0,1991.0,24318000,63.7,14194.0,21300.0,Uzbekiston,Republic,Islam Karimov,3503.0,UZ

In [13]:
country.query("continent == 'Asia' & indepyear >= 1991")

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
12,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotarjan,126.0,AM
15,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144.0,AZ
55,GEO,Georgia,Asia,Middle East,69700.0,1991.0,4968000,64.5,6064.0,5924.0,Sakartvelo,Republic,Eduard evardnadze,905.0,GE
90,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
94,KGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900.0,1991.0,4699000,63.4,1626.0,1767.0,Kyrgyzstan,Republic,Askar Akajev,2253.0,KG
197,TJK,Tajikistan,Asia,Southern and Central Asia,143100.0,1991.0,6188000,64.1,1990.0,1056.0,Toçikiston,Republic,Emomali Rahmonov,3261.0,TJ
210,TKM,Turkmenistan,Asia,Southern and Central Asia,488100.0,1991.0,4459000,60.9,4397.0,2000.0,Türkmenostan,Republic,Saparmurad Nijazov,3419.0,TM
219,UZB,Uzbekistan,Asia,Southern and Central Asia,447400.0,1991.0,24318000,63.7,14194.0,21300.0,Uzbekiston,Republic,Islam Karimov,3503.0,UZ

In [14]:
country.\
query("(continent == 'Asia'| continent == 'Africa') & indepyear >= 1991").\
project(['name', 'continent', 'indepyear'])

             name continent  indepyear
12        Armenia      Asia     1991.0
15     Azerbaijan      Asia     1991.0
45        Eritrea    Africa     1993.0
55        Georgia      Asia     1991.0
90      Kazakstan      Asia     1991.0
94     Kyrgyzstan      Asia     1991.0
197    Tajikistan      Asia     1991.0
210  Turkmenistan      Asia     1991.0
219    Uzbekistan      Asia     1991.0

# Relational Algebra: Sort

In [9]:
country.query('indepyear < 1200').project(['name', 'indepyear']).sort(['indepyear'])

               name  indepyear
93            China    -1523.0
48         Ethiopia    -1000.0
81            Japan     -660.0
200         Denmark      800.0
170          Sweden      836.0
164          France      843.0
180      San Marino      885.0
29   United Kingdom     1066.0
159        Portugal     1143.0

In [10]:
country.query('indepyear < 1200').project(['name', 'indepyear']).sort(['indepyear'], ascending=False)

               name  indepyear
159        Portugal     1143.0
29   United Kingdom     1066.0
180      San Marino      885.0
164          France      843.0
170          Sweden      836.0
200         Denmark      800.0
81            Japan     -660.0
48         Ethiopia    -1000.0
93            China    -1523.0

# SQL: Structured Query Language

# SQL

SQL is the language of database management systems
Database Management System (DBMS) provides:

* efficient
* reliable
* convenient
* safe
* multi-user

storage of and access to massive amounts of persistent data

Many Database management systems are built on the relational model

* Postgresql, MySQL, SQLLITE

Relation == Table

Tuple == Row

# Using SQL Magic in Jupyter Notebooks

* Run the cell with a single directive `%load_ext sql` to load sql extension.

* Every cell with SQL code must start with either `%sql` (for a one-liner) or `%%sql` (the whole cell is treated as SQL)

* You need to connect to a database: `postgres://username@localhost/dbname`
  * Password is optional: `postgres://username:password@localhost/dbname`
  * By default dbname is the same as your username

In [16]:
%load_ext sql

In [17]:
%%sql
postgres://yasiro01@localhost/world

'Connected: yasiro01@world'

# SQL: Select

In [18]:
%%sql

select name from country;

239 rows affected.

[('Afghanistan',),
 ('Netherlands',),
 ('Netherlands Antilles',),
 ('Albania',),
 ('Algeria',),
 ('American Samoa',),
 ('Andorra',),
 ('Angola',),
 ('Anguilla',),
 ('Antigua and Barbuda',),
 ('United Arab Emirates',),
 ('Argentina',),
 ('Armenia',),
 ('Aruba',),
 ('Australia',),
 ('Azerbaijan',),
 ('Bahamas',),
 ('Bahrain',),
 ('Bangladesh',),
 ('Barbados',),
 ('Belgium',),
 ('Belize',),
 ('Benin',),
 ('Bermuda',),
 ('Bhutan',),
 ('Bolivia',),
 ('Bosnia and Herzegovina',),
 ('Botswana',),
 ('Brazil',),
 ('United Kingdom',),
 ('Virgin Islands, British',),
 ('Brunei',),
 ('Bulgaria',),
 ('Burkina Faso',),
 ('Burundi',),
 ('Cayman Islands',),
 ('Chile',),
 ('Cook Islands',),
 ('Costa Rica',),
 ('Djibouti',),
 ('Dominica',),
 ('Dominican Republic',),
 ('Ecuador',),
 ('Egypt',),
 ('El Salvador',),
 ('Eritrea',),
 ('Spain',),
 ('South Africa',),
 ('Ethiopia',),
 ('Fiji Islands',),
 ('Philippines',),
 ('Faroe Islands',),
 ('Gabon',),
 ('Gambia',),
 ('Georgia',),
 ('Ghana',),
 ('Gibraltar',),
 ('Grenada',),
 ('Greenland',),
 ('Guadeloupe',),
 ('Guam',),
 ('Guatemala',),
 ('Guinea',),
 ('Guinea-Bissau',),
 ('Guyana',),
 ('Haiti',),
 ('Honduras',),
 ('Hong Kong',),
 ('Indonesia',),
 ('India',),
 ('Iraq',),
 ('Iran',),
 ('Ireland',),
 ('Iceland',),
 ('Israel',),
 ('Italy',),
 ('East Timor',),
 ('Austria',),
 ('Jamaica',),
 ('Japan',),
 ('Yemen',),
 ('Jordan',),
 ('Yugoslavia',),
 ('Cambodia',),
 ('Cameroon',),
 ('Canada',),
 ('Cape Verde',),
 ('Kazakstan',),
 ('Kenya',),
 ('Central African Republic',),
 ('China',),
 ('Kyrgyzstan',),
 ('Kiribati',),
 ('Colombia',),
 ('Comoros',),
 ('Congo',),
 ('Congo, The Democratic Republic of the',),
 ('North Korea',),
 ('South Korea',),
 ('Greece',),
 ('Croatia',),
 ('Cuba',),
 ('Kuwait',),
 ('Cyprus',),
 ('Laos',),
 ('Latvia',),
 ('Lesotho',),
 ('Lebanon',),
 ('Liberia',),
 ('Libyan Arab Jamahiriya',),
 ('Liechtenstein',),
 ('Lithuania',),
 ('Luxembourg',),
 ('Western Sahara',),
 ('Macao',),
 ('Madagascar',),
 ('Macedonia',),
 ('Malawi',),
 ('Maldives',),
 ('Malaysia',),
 ('Mali',),
 ('Malta',),
 ('Morocco',),
 ('Marshall Islands',),
 ('Martinique',),
 ('Mauritania',),
 ('Mauritius',),
 ('Mayotte',),
 ('Mexico',),
 ('Micronesia, Federated States of',),
 ('Moldova',),
 ('Monaco',),
 ('Mongolia',),
 ('Montserrat',),
 ('Mozambique',),
 ('Myanmar',),
 ('Namibia',),
 ('Nauru',),
 ('Nepal',),
 ('Nicaragua',),
 ('Niger',),
 ('Nigeria',),
 ('Norway',),
 ('Côte d\x92Ivoire',),
 ('Oman',),
 ('Pakistan',),
 ('Palau',),
 ('Panama',),
 ('Papua New Guinea',),
 ('Paraguay',),
 ('Peru',),
 ('Northern Mariana Islands',),
 ('Portugal',),
 ('Puerto Rico',),
 ('Poland',),
 ('Equatorial Guinea',),
 ('Qatar',),
 ('France',),
 ('French Guiana',),
 ('French Polynesia',),
 ('Réunion',),
 ('Romania',),
 ('Rwanda',),
 ('Sweden',),
 ('Saint Helena',),
 ('Saint Kitts and Nevis',),
 ('Saint Lucia',),
 ('Saint Vincent and the Grenadines',),
 ('Saint Pierre and Miquelon',),
 ('Germany',),
 ('Solomon Islands',),
 ('Zambia',),
 ('Samoa',),
 ('San Marino',),
 ('Sao Tome and Principe',),
 ('Saudi Arabia',),
 ('Senegal',),
 ('Seychelles',),
 ('Sierra Leone',),
 ('Singapore',),
 ('Slovakia',),
 ('Slovenia',),
 ('Somalia',),
 ('Sri Lanka',),
 ('Sudan',),
 ('Finland',),
 ('Suriname',),
 ('Swaziland',),
 ('Switzerland',),
 ('Syria',),
 ('Tajikistan',),
 ('Taiwan',),
 ('Tanzania',),
 ('Denmark',),
 ('Thailand',),
 ('Togo',),
 ('Tonga',),
 ('Trinidad and Tobago',),
 ('Chad',),
 ('Czech Republic',),
 ('Tunisia',),
 ('Turkey',),
 ('Turkmenistan',),
 ('Turks and Caicos Islands',),
 ('Tuvalu',),
 ('Uganda',),
 ('Ukraine',),
 ('Hungary',),
 ('Uruguay',),
 ('New Caledonia',),
 ('New Zealand',),
 ('Uzbekistan',),
 ('Belarus',),
 ('Vanuatu',),
 ('Venezuela',),
 ('Russian Federation',),
 ('Vietnam',),
 ('Estonia',),
 ('United States',),
 ('Virgin Islands, U.S.',),
 ('Zimbabwe',),
 ('Palestine',),
 ('Falkland Islands',),
 ('Svalbard and Jan Mayen',),
 ('Niue',),
 ('Pitcairn',),
 ('Tokelau',),
 ('Wallis and Futuna',),
 ('Holy See (Vatican City State)',),
 ('Antarctica',),
 ('Bouvet Island',),
 ('British Indian Ocean Territory',),
 ('South Georgia and the South Sandwich Islands',),
 ('Heard Island and McDonald Islands',),
 ('French Southern territories',),
 ('United States Minor Outlying Islands',),
 ('Christmas Island',),
 ('Cocos (Keeling) Islands',),
 ('Norfolk Island',)]

# SQL: Basic Syntax

* Trailing semicolon is optional
* It's recommended to start each clause on a new line

In [19]:
%%sql

select name
from country

239 rows affected.

[('Afghanistan',),
 ('Netherlands',),
 ('Netherlands Antilles',),
 ('Albania',),
 ('Algeria',),
 ('American Samoa',),
 ('Andorra',),
 ('Angola',),
 ('Anguilla',),
 ('Antigua and Barbuda',),
 ('United Arab Emirates',),
 ('Argentina',),
 ('Armenia',),
 ('Aruba',),
 ('Australia',),
 ('Azerbaijan',),
 ('Bahamas',),
 ('Bahrain',),
 ('Bangladesh',),
 ('Barbados',),
 ('Belgium',),
 ('Belize',),
 ('Benin',),
 ('Bermuda',),
 ('Bhutan',),
 ('Bolivia',),
 ('Bosnia and Herzegovina',),
 ('Botswana',),
 ('Brazil',),
 ('United Kingdom',),
 ('Virgin Islands, British',),
 ('Brunei',),
 ('Bulgaria',),
 ('Burkina Faso',),
 ('Burundi',),
 ('Cayman Islands',),
 ('Chile',),
 ('Cook Islands',),
 ('Costa Rica',),
 ('Djibouti',),
 ('Dominica',),
 ('Dominican Republic',),
 ('Ecuador',),
 ('Egypt',),
 ('El Salvador',),
 ('Eritrea',),
 ('Spain',),
 ('South Africa',),
 ('Ethiopia',),
 ('Fiji Islands',),
 ('Philippines',),
 ('Faroe Islands',),
 ('Gabon',),
 ('Gambia',),
 ('Georgia',),
 ('Ghana',),
 ('Gibraltar',),
 ('Grenada',),
 ('Greenland',),
 ('Guadeloupe',),
 ('Guam',),
 ('Guatemala',),
 ('Guinea',),
 ('Guinea-Bissau',),
 ('Guyana',),
 ('Haiti',),
 ('Honduras',),
 ('Hong Kong',),
 ('Indonesia',),
 ('India',),
 ('Iraq',),
 ('Iran',),
 ('Ireland',),
 ('Iceland',),
 ('Israel',),
 ('Italy',),
 ('East Timor',),
 ('Austria',),
 ('Jamaica',),
 ('Japan',),
 ('Yemen',),
 ('Jordan',),
 ('Yugoslavia',),
 ('Cambodia',),
 ('Cameroon',),
 ('Canada',),
 ('Cape Verde',),
 ('Kazakstan',),
 ('Kenya',),
 ('Central African Republic',),
 ('China',),
 ('Kyrgyzstan',),
 ('Kiribati',),
 ('Colombia',),
 ('Comoros',),
 ('Congo',),
 ('Congo, The Democratic Republic of the',),
 ('North Korea',),
 ('South Korea',),
 ('Greece',),
 ('Croatia',),
 ('Cuba',),
 ('Kuwait',),
 ('Cyprus',),
 ('Laos',),
 ('Latvia',),
 ('Lesotho',),
 ('Lebanon',),
 ('Liberia',),
 ('Libyan Arab Jamahiriya',),
 ('Liechtenstein',),
 ('Lithuania',),
 ('Luxembourg',),
 ('Western Sahara',),
 ('Macao',),
 ('Madagascar',),
 ('Macedonia',),
 ('Malawi',),
 ('Maldives',),
 ('Malaysia',),
 ('Mali',),
 ('Malta',),
 ('Morocco',),
 ('Marshall Islands',),
 ('Martinique',),
 ('Mauritania',),
 ('Mauritius',),
 ('Mayotte',),
 ('Mexico',),
 ('Micronesia, Federated States of',),
 ('Moldova',),
 ('Monaco',),
 ('Mongolia',),
 ('Montserrat',),
 ('Mozambique',),
 ('Myanmar',),
 ('Namibia',),
 ('Nauru',),
 ('Nepal',),
 ('Nicaragua',),
 ('Niger',),
 ('Nigeria',),
 ('Norway',),
 ('Côte d\x92Ivoire',),
 ('Oman',),
 ('Pakistan',),
 ('Palau',),
 ('Panama',),
 ('Papua New Guinea',),
 ('Paraguay',),
 ('Peru',),
 ('Northern Mariana Islands',),
 ('Portugal',),
 ('Puerto Rico',),
 ('Poland',),
 ('Equatorial Guinea',),
 ('Qatar',),
 ('France',),
 ('French Guiana',),
 ('French Polynesia',),
 ('Réunion',),
 ('Romania',),
 ('Rwanda',),
 ('Sweden',),
 ('Saint Helena',),
 ('Saint Kitts and Nevis',),
 ('Saint Lucia',),
 ('Saint Vincent and the Grenadines',),
 ('Saint Pierre and Miquelon',),
 ('Germany',),
 ('Solomon Islands',),
 ('Zambia',),
 ('Samoa',),
 ('San Marino',),
 ('Sao Tome and Principe',),
 ('Saudi Arabia',),
 ('Senegal',),
 ('Seychelles',),
 ('Sierra Leone',),
 ('Singapore',),
 ('Slovakia',),
 ('Slovenia',),
 ('Somalia',),
 ('Sri Lanka',),
 ('Sudan',),
 ('Finland',),
 ('Suriname',),
 ('Swaziland',),
 ('Switzerland',),
 ('Syria',),
 ('Tajikistan',),
 ('Taiwan',),
 ('Tanzania',),
 ('Denmark',),
 ('Thailand',),
 ('Togo',),
 ('Tonga',),
 ('Trinidad and Tobago',),
 ('Chad',),
 ('Czech Republic',),
 ('Tunisia',),
 ('Turkey',),
 ('Turkmenistan',),
 ('Turks and Caicos Islands',),
 ('Tuvalu',),
 ('Uganda',),
 ('Ukraine',),
 ('Hungary',),
 ('Uruguay',),
 ('New Caledonia',),
 ('New Zealand',),
 ('Uzbekistan',),
 ('Belarus',),
 ('Vanuatu',),
 ('Venezuela',),
 ('Russian Federation',),
 ('Vietnam',),
 ('Estonia',),
 ('United States',),
 ('Virgin Islands, U.S.',),
 ('Zimbabwe',),
 ('Palestine',),
 ('Falkland Islands',),
 ('Svalbard and Jan Mayen',),
 ('Niue',),
 ('Pitcairn',),
 ('Tokelau',),
 ('Wallis and Futuna',),
 ('Holy See (Vatican City State)',),
 ('Antarctica',),
 ('Bouvet Island',),
 ('British Indian Ocean Territory',),
 ('South Georgia and the South Sandwich Islands',),
 ('Heard Island and McDonald Islands',),
 ('French Southern territories',),
 ('United States Minor Outlying Islands',),
 ('Christmas Island',),
 ('Cocos (Keeling) Islands',),
 ('Norfolk Island',)]

In [20]:
%%sql

select name, region
from country
where continent = 'Asia'

51 rows affected.

[('Afghanistan', 'Southern and Central Asia'),
 ('United Arab Emirates', 'Middle East'),
 ('Armenia', 'Middle East'),
 ('Azerbaijan', 'Middle East'),
 ('Bahrain', 'Middle East'),
 ('Bangladesh', 'Southern and Central Asia'),
 ('Bhutan', 'Southern and Central Asia'),
 ('Brunei', 'Southeast Asia'),
 ('Philippines', 'Southeast Asia'),
 ('Georgia', 'Middle East'),
 ('Hong Kong', 'Eastern Asia'),
 ('Indonesia', 'Southeast Asia'),
 ('India', 'Southern and Central Asia'),
 ('Iraq', 'Middle East'),
 ('Iran', 'Southern and Central Asia'),
 ('Israel', 'Middle East'),
 ('East Timor', 'Southeast Asia'),
 ('Japan', 'Eastern Asia'),
 ('Yemen', 'Middle East'),
 ('Jordan', 'Middle East'),
 ('Cambodia', 'Southeast Asia'),
 ('Kazakstan', 'Southern and Central Asia'),
 ('China', 'Eastern Asia'),
 ('Kyrgyzstan', 'Southern and Central Asia'),
 ('North Korea', 'Eastern Asia'),
 ('South Korea', 'Eastern Asia'),
 ('Kuwait', 'Middle East'),
 ('Cyprus', 'Middle East'),
 ('Laos', 'Southeast Asia'),
 ('Lebanon', 'Middle East'),
 ('Macao', 'Eastern Asia'),
 ('Maldives', 'Southern and Central Asia'),
 ('Malaysia', 'Southeast Asia'),
 ('Mongolia', 'Eastern Asia'),
 ('Myanmar', 'Southeast Asia'),
 ('Nepal', 'Southern and Central Asia'),
 ('Oman', 'Middle East'),
 ('Pakistan', 'Southern and Central Asia'),
 ('Qatar', 'Middle East'),
 ('Saudi Arabia', 'Middle East'),
 ('Singapore', 'Southeast Asia'),
 ('Sri Lanka', 'Southern and Central Asia'),
 ('Syria', 'Middle East'),
 ('Tajikistan', 'Southern and Central Asia'),
 ('Taiwan', 'Eastern Asia'),
 ('Thailand', 'Southeast Asia'),
 ('Turkey', 'Middle East'),
 ('Turkmenistan', 'Southern and Central Asia'),
 ('Uzbekistan', 'Southern and Central Asia'),
 ('Vietnam', 'Southeast Asia'),
 ('Palestine', 'Middle East')]

In [21]:
%%sql

select *
from country
where continent = 'Asia'

51 rows affected.

[('AFG', 'Afghanistan', 'Asia', 'Southern and Central Asia', 652090.0, 1919, 22720000, 45.9, Decimal('5976.00'), None, 'Afganistan/Afqanestan', 'Islamic Emirate', 'Mohammad Omar', 1, 'AF'),
 ('ARE', 'United Arab Emirates', 'Asia', 'Middle East', 83600.0, 1971, 2441000, 74.1, Decimal('37966.00'), Decimal('36846.00'), 'Al-Imarat al-´Arabiya al-Muttahida', 'Emirate Federation', 'Zayid bin Sultan al-Nahayan', 65, 'AE'),
 ('ARM', 'Armenia', 'Asia', 'Middle East', 29800.0, 1991, 3520000, 66.4, Decimal('1813.00'), Decimal('1627.00'), 'Hajastan', 'Republic', 'Robert Kot\x9aarjan', 126, 'AM'),
 ('AZE', 'Azerbaijan', 'Asia', 'Middle East', 86600.0, 1991, 7734000, 62.9, Decimal('4127.00'), Decimal('4100.00'), 'Azärbaycan', 'Federal Republic', 'Heydär Äliyev', 144, 'AZ'),
 ('BHR', 'Bahrain', 'Asia', 'Middle East', 694.0, 1971, 617000, 73.0, Decimal('6366.00'), Decimal('6097.00'), 'Al-Bahrayn', 'Monarchy (Emirate)', 'Hamad ibn Isa al-Khalifa', 149, 'BH'),
 ('BGD', 'Bangladesh', 'Asia', 'Southern and Central Asia', 143998.0, 1971, 129155000, 60.2, Decimal('32852.00'), Decimal('31966.00'), 'Bangladesh', 'Republic', 'Shahabuddin Ahmad', 150, 'BD'),
 ('BTN', 'Bhutan', 'Asia', 'Southern and Central Asia', 47000.0, 1910, 2124000, 52.4, Decimal('372.00'), Decimal('383.00'), 'Druk-Yul', 'Monarchy', 'Jigme Singye Wangchuk', 192, 'BT'),
 ('BRN', 'Brunei', 'Asia', 'Southeast Asia', 5765.0, 1984, 328000, 73.6, Decimal('11705.00'), Decimal('12460.00'), 'Brunei Darussalam', 'Monarchy (Sultanate)', 'Haji Hassan al-Bolkiah', 538, 'BN'),
 ('PHL', 'Philippines', 'Asia', 'Southeast Asia', 300000.0, 1946, 75967000, 67.5, Decimal('65107.00'), Decimal('82239.00'), 'Pilipinas', 'Republic', 'Gloria Macapagal-Arroyo', 766, 'PH'),
 ('GEO', 'Georgia', 'Asia', 'Middle East', 69700.0, 1991, 4968000, 64.5, Decimal('6064.00'), Decimal('5924.00'), 'Sakartvelo', 'Republic', 'Eduard \x8aevardnadze', 905, 'GE'),
 ('HKG', 'Hong Kong', 'Asia', 'Eastern Asia', 1075.0, None, 6782000, 79.5, Decimal('166448.00'), Decimal('173610.00'), 'Xianggang/Hong Kong', 'Special Administrative Region of China', 'Jiang Zemin', 937, 'HK'),
 ('IDN', 'Indonesia', 'Asia', 'Southeast Asia', 1904570.0, 1945, 212107000, 68.0, Decimal('84982.00'), Decimal('215002.00'), 'Indonesia', 'Republic', 'Abdurrahman Wahid', 939, 'ID'),
 ('IND', 'India', 'Asia', 'Southern and Central Asia', 3287260.0, 1947, 1013662000, 62.5, Decimal('447114.00'), Decimal('430572.00'), 'Bharat/India', 'Federal Republic', 'Kocheril Raman Narayanan', 1109, 'IN'),
 ('IRQ', 'Iraq', 'Asia', 'Middle East', 438317.0, 1932, 23115000, 66.5, Decimal('11500.00'), None, 'Al-´Iraq', 'Republic', 'Saddam Hussein al-Takriti', 1365, 'IQ'),
 ('IRN', 'Iran', 'Asia', 'Southern and Central Asia', 1648200.0, 1906, 67702000, 69.7, Decimal('195746.00'), Decimal('160151.00'), 'Iran', 'Islamic Republic', 'Ali Mohammad Khatami-Ardakani', 1380, 'IR'),
 ('ISR', 'Israel', 'Asia', 'Middle East', 21056.0, 1948, 6217000, 78.6, Decimal('97477.00'), Decimal('98577.00'), 'Yisra\x92el/Isra\x92il', 'Republic', 'Moshe Katzav', 1450, 'IL'),
 ('TMP', 'East Timor', 'Asia', 'Southeast Asia', 14874.0, None, 885000, 46.0, Decimal('0.00'), None, 'Timor Timur', 'Administrated by the UN', 'José Alexandre Gusmão', 1522, 'TP'),
 ('JPN', 'Japan', 'Asia', 'Eastern Asia', 377829.0, -660, 126714000, 80.7, Decimal('3787042.00'), Decimal('4192638.00'), 'Nihon/Nippon', 'Constitutional Monarchy', 'Akihito', 1532, 'JP'),
 ('YEM', 'Yemen', 'Asia', 'Middle East', 527968.0, 1918, 18112000, 59.8, Decimal('6041.00'), Decimal('5729.00'), 'Al-Yaman', 'Republic', 'Ali Abdallah Salih', 1780, 'YE'),
 ('JOR', 'Jordan', 'Asia', 'Middle East', 88946.0, 1946, 5083000, 77.4, Decimal('7526.00'), Decimal('7051.00'), 'Al-Urdunn', 'Constitutional Monarchy', 'Abdullah II', 1786, 'JO'),
 ('KHM', 'Cambodia', 'Asia', 'Southeast Asia', 181035.0, 1953, 11168000, 56.5, Decimal('5121.00'), Decimal('5670.00'), 'Kâmpuchéa', 'Constitutional Monarchy', 'Norodom Sihanouk', 1800, 'KH'),
 ('KAZ', 'Kazakstan', 'Asia', 'Southern and Central Asia', 2724900.0, 1991, 16223000, 63.2, Decimal('24375.00'), Decimal('23383.00'), 'Qazaqstan', 'Republic', 'Nursultan Nazarbajev', 1864, 'KZ'),
 ('CHN', 'China', 'Asia', 'Eastern Asia', 9572900.0, -1523, 1277558000, 71.4, Decimal('982268.00'), Decimal('917719.00'), 'Zhongquo', "People'sRepublic", 'Jiang Zemin', 1891, 'CN'),
 ('KGZ', 'Kyrgyzstan', 'Asia', 'Southern and Central Asia', 199900.0, 1991, 4699000, 63.4, Decimal('1626.00'), Decimal('1767.00'), 'Kyrgyzstan', 'Republic', 'Askar Akajev', 2253, 'KG'),
 ('PRK', 'North Korea', 'Asia', 'Eastern Asia', 120538.0, 1948, 24039000, 70.7, Decimal('5332.00'), None, 'Choson Minjujuui In´min Konghwaguk (Bukhan)', 'Socialistic Republic', 'Kim Jong-il', 2318, 'KP'),
 ('KOR', 'South Korea', 'Asia', 'Eastern Asia', 99434.0, 1948, 46844000, 74.4, Decimal('320749.00'), Decimal('442544.00'), 'Taehan Min\x92guk (Namhan)', 'Republic', 'Kim Dae-jung', 2331, 'KR'),
 ('KWT', 'Kuwait', 'Asia', 'Middle East', 17818.0, 1961, 1972000, 76.1, Decimal('27037.00'), Decimal('30373.00'), 'Al-Kuwayt', 'Constitutional Monarchy (Emirate)', 'Jabir al-Ahmad al-Jabir al-Sabah', 2429, 'KW'),
 ('CYP', 'Cyprus', 'Asia', 'Middle East', 9251.0, 1960, 754700, 76.7, Decimal('9333.00'), Decimal('8246.00'), 'Kýpros/Kibris', 'Republic', 'Glafkos Klerides', 2430, 'CY'),
 ('LAO', 'Laos', 'Asia', 'Southeast Asia', 236800.0, 1953, 5433000, 53.1, Decimal('1292.00'), Decimal('1746.00'), 'Lao', 'Republic', 'Khamtay Siphandone', 2432, 'LA'),
 ('LBN', 'Lebanon', 'Asia', 'Middle East', 10400.0, 1941, 3282000, 71.3, Decimal('17121.00'), Decimal('15129.00'), 'Lubnan', 'Republic', 'Émile Lahoud', 2438, 'LB'),
 ('MAC', 'Macao', 'Asia', 'Eastern Asia', 18.0, None, 473000, 81.6, Decimal('5749.00'), Decimal('5940.00'), 'Macau/Aomen', 'Special Administrative Region of China', 'Jiang Zemin', 2454, 'MO'),
 ('MDV', 'Maldives', 'Asia', 'Southern and Central Asia', 298.0, 1965, 286000, 62.2, Decimal('199.00'), None, 'Dhivehi Raajje/Maldives', 'Republic', 'Maumoon Abdul Gayoom', 2463, 'MV'),
 ('MYS', 'Malaysia', 'Asia', 'Southeast Asia', 329758.0, 1957, 22244000, 70.8, Decimal('69213.00'), Decimal('97884.00'), 'Malaysia', 'Constitutional Monarchy, Federation', 'Salahuddin Abdul Aziz Shah Alhaj', 2464, 'MY'),
 ('MNG', 'Mongolia', 'Asia', 'Eastern Asia', 1566500.0, 1921, 2662000, 67.3, Decimal('1043.00'), Decimal('933.00'), 'Mongol Uls', 'Republic', 'Natsagiin Bagabandi', 2696, 'MN'),
 ('MMR', 'Myanmar', 'Asia', 'Southeast Asia', 676578.0, 1948, 45611000, 54.9, Decimal('180375.00'), Decimal('171028.00'), 'Myanma Pye', 'Republic', 'kenraali Than Shwe', 2710, 'MM'),
 ('NPL', 'Nepal', 'Asia', 'Southern and Central Asia', 147181.0, 1769, 23930000, 57.8, Decimal('4768.00'), Decimal('4837.00'), 'Nepal', 'Constitutional Monarchy', 'Gyanendra Bir Bikram', 2729, 'NP'),
 ('OMN', 'Oman', 'Asia', 'Middle East', 309500.0, 1951, 2542000, 71.8, Decimal('16904.00'), Decimal('16153.00'), '´Uman', 'Monarchy (Sultanate)', 'Qabus ibn Sa´id', 2821, 'OM'),
 ('PAK', 'Pakistan', 'Asia', 'Southern and Central Asia', 796095.0, 1947, 156483000, 61.1, Decimal('61289.00'), Decimal('58549.00'), 'Pakistan', 'Republic', 'Mohammad Rafiq Tarar', 2831, 'PK'),
 ('QAT', 'Qatar', 'Asia', 'Middle East', 11000.0, 1971, 599000, 72.4, Decimal('9472.00'), Decimal('8920.00'), 'Qatar', 'Monarchy', 'Hamad ibn Khalifa al-Thani', 2973, 'QA'),
 ('SAU', 'Saudi Arabia', 'Asia', 'Middle East', 2149690.0, 1932, 21607000, 67.8, Decimal('137635.00'), Decimal('146171.00'), 'Al-´Arabiya as-Sa´udiya', 'Monarchy', 'Fahd ibn Abdul-Aziz al-Sa´ud', 3173, 'SA'),
 ('SGP', 'Singapore', 'Asia', 'Southeast Asia', 618.0, 1965, 3567000, 80.1, Decimal('86503.00'), Decimal('96318.00'), 'Singapore/Singapura/Xinjiapo/Singapur', 'Republic', 'Sellapan Rama Nathan', 3208, 'SG'),
 ('LKA', 'Sri Lanka', 'Asia', 'Southern and Central Asia', 65610.0, 1948, 18827000, 71.8, Decimal('15706.00'), Decimal('15091.00'), 'Sri Lanka/Ilankai', 'Republic', 'Chandrika Kumaratunga', 3217, 'LK'),
 ('SYR', 'Syria', 'Asia', 'Middle East', 185180.0, 1941, 16125000, 68.5, Decimal('65984.00'), Decimal('64926.00'), 'Suriya', 'Republic', 'Bashar al-Assad', 3250, 'SY'),
 ('TJK', 'Tajikistan', 'Asia', 'Southern and Central Asia', 143100.0, 1991, 6188000, 64.1, Decimal('1990.00'), Decimal('1056.00'), 'Toçikiston', 'Republic', 'Emomali Rahmonov', 3261, 'TJ'),
 ('TWN', 'Taiwan', 'Asia', 'Eastern Asia', 36188.0, 1945, 22256000, 76.4, Decimal('256254.00'), Decimal('263451.00'), 'T\x92ai-wan', 'Republic', 'Chen Shui-bian', 3263, 'TW'),
 ('THA', 'Thailand', 'Asia', 'Southeast Asia', 513115.0, 1350, 61399000, 68.6, Decimal('116416.00'), Decimal('153907.00'), 'Prathet Thai', 'Constitutional Monarchy', 'Bhumibol Adulyadej', 3320, 'TH'),
 ('TUR', 'Turkey', 'Asia', 'Middle East', 774815.0, 1923, 66591000, 71.0, Decimal('210721.00'), Decimal('189122.00'), 'Türkiye', 'Republic', 'Ahmet Necdet Sezer', 3358, 'TR'),
 ('TKM', 'Turkmenistan', 'Asia', 'Southern and Central Asia', 488100.0, 1991, 4459000, 60.9, Decimal('4397.00'), Decimal('2000.00'), 'Türkmenostan', 'Republic', 'Saparmurad Nijazov', 3419, 'TM'),
 ('UZB', 'Uzbekistan', 'Asia', 'Southern and Central Asia', 447400.0, 1991, 24318000, 63.7, Decimal('14194.00'), Decimal('21300.00'), 'Uzbekiston', 'Republic', 'Islam Karimov', 3503, 'UZ'),
 ('VNM', 'Vietnam', 'Asia', 'Southeast Asia', 331689.0, 1945, 79832000, 69.3, Decimal('21929.00'), Decimal('22834.00'), 'Viêt Nam', 'Socialistic Republic', 'Trân Duc Luong', 3770, 'VN'),
 ('PSE', 'Palestine', 'Asia', 'Middle East', 6257.0, None, 3101000, 71.4, Decimal('4173.00'), None, 'Filastin', 'Autonomous Area', 'Yasser (Yasir) Arafat', 4074, 'PS')]

# Relational Algebra vs SQL

Relational Allgebra operations and SQL queries allow you to retrieve data. The results are similar.

In [15]:
country.query('name == "United States"').project(['name', 'indepyear'])

              name  indepyear
228  United States     1776.0

In [16]:
%%sql

select name, indepyear
from country
where name = 'United States'

1 rows affected.

[('United States', 1776)]

In [17]:
country.project(['name', 'indepyear']).query('indepyear < 1200')

               name  indepyear
29   United Kingdom     1066.0
48         Ethiopia    -1000.0
81            Japan     -660.0
93            China    -1523.0
159        Portugal     1143.0
164          France      843.0
170          Sweden      836.0
180      San Marino      885.0
200         Denmark      800.0

In [18]:
%%sql

select name, indepyear
from country
where indepyear < 1200

9 rows affected.

[('United Kingdom', 1066),
 ('Ethiopia', -1000),
 ('Japan', -660),
 ('China', -1523),
 ('Portugal', 1143),
 ('France', 843),
 ('Sweden', 836),
 ('San Marino', 885),
 ('Denmark', 800)]

# SQL: Ordering

In [19]:
%%sql

select name, indepyear
from country
where indepyear < 1200
order by indepyear

9 rows affected.

[('China', -1523),
 ('Ethiopia', -1000),
 ('Japan', -660),
 ('Denmark', 800),
 ('Sweden', 836),
 ('France', 843),
 ('San Marino', 885),
 ('United Kingdom', 1066),
 ('Portugal', 1143)]

In [20]:
%%sql

select name, indepyear
from country
where indepyear < 1200
order by indepyear desc

9 rows affected.

[('Portugal', 1143),
 ('United Kingdom', 1066),
 ('San Marino', 885),
 ('France', 843),
 ('Sweden', 836),
 ('Denmark', 800),
 ('Japan', -660),
 ('Ethiopia', -1000),
 ('China', -1523)]

# SQL: Ordering

* Query results can be sorted in ascending (default, asc) or descending (desc) order

* You can order by multiple fields

## Select all countries and territories under the rule of Queen Beatrix

In [21]:
%%sql

select name, headofstate
from country
where headofstate = 'Beatrix'
order by headofstate

3 rows affected.

[('Netherlands', 'Beatrix'),
 ('Netherlands Antilles', 'Beatrix'),
 ('Aruba', 'Beatrix')]

In [22]:
%%sql

select name, headofstate
from country
where headofstate = 'Beatrix' or headofstate = 'George W. Bush'
order by headofstate, name

10 rows affected.

[('Aruba', 'Beatrix'),
 ('Netherlands', 'Beatrix'),
 ('Netherlands Antilles', 'Beatrix'),
 ('American Samoa', 'George W. Bush'),
 ('Guam', 'George W. Bush'),
 ('Northern Mariana Islands', 'George W. Bush'),
 ('Puerto Rico', 'George W. Bush'),
 ('United States', 'George W. Bush'),
 ('United States Minor Outlying Islands', 'George W. Bush'),
 ('Virgin Islands, U.S.', 'George W. Bush')]

# SQL: The Oldest Country in the World

In [23]:
%%sql

select name, indepyear
from country
order by indepyear
limit 1

1 rows affected.

[('China', -1523)]

# SQL: The Newest Country in the World

In [24]:
%%sql

select name, indepyear
from country
where indepyear is not null
order by indepyear desc
limit 1

1 rows affected.

[('Palau', 1994)]