# Asking Questions about Countries

## Part 1:  The Questions

![](country.png)

### Brainstorm some Questions about countries

1. List all data about all countries in Africa
1. List all data about all countries in the Middle East region
1. List only the country name and region for the countries in the Middle East region
1. Show the country name and life expectancy of the 5 countries with the longest life expectancy
1. Show the country name, population, and gnp of the 5 countries with the smallest gnp
1. Show all of the distinct regions of the world
1. List the country name and gnp of all of the countries that are Monarchies
1. List the country name, governmentform and population of the countries that are any kind of Monarchy (Monarchy, Constitutional Monarchy, or Monarchy (Sultanate)
1. List the country name and gnp of the countries in Southeast Asia with population less than 5 million
1. List the country names, gnp, and population where the new gnp is more than the old gnp

## Part 2:  Using Relational Algebra

* when using relational algebra, all of your notebooks and homework are going to start out a lot like this

* option `sep='|'` specifies the separator used in the *csv* file (default is comma)

In [1]:
from reframe import Relation

country = Relation('/home/faculty/yasiro01/pub/country.csv', sep='|')

We will answer the following questions and more using the following relational operators

* project
* query
* sort
* head

### List all data about all countries in Africa

In [2]:
country.query("continent == 'Africa'").head(5)

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
4,DZA,Algeria,Africa,Northern Africa,2381740.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ
7,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
22,BEN,Benin,Africa,Western Africa,112622.0,1960.0,6097000,50.2,2357.0,2141.0,Bénin,Republic,Mathieu Kérékou,187.0,BJ
27,BWA,Botswana,Africa,Southern Africa,581730.0,1966.0,1622000,39.3,4834.0,4935.0,Botswana,Republic,Festus G. Mogae,204.0,BW
33,BFA,Burkina Faso,Africa,Western Africa,274000.0,1960.0,11937000,46.7,2425.0,2201.0,Burkina Faso,Republic,Blaise Compaoré,549.0,BF

### List all data about all countries in Africa using SQL

In [3]:
%load_ext sql

In [4]:
%%sql

postgres://yasiro01@localhost/world

'Connected: yasiro01@world'

In [5]:
%%sql

select *
from country
where continent = 'Africa'

58 rows affected.

[('DZA', 'Algeria', 'Africa', 'Northern Africa', 2381740.0, 1962, 31471000, 69.7, Decimal('49982.00'), Decimal('46966.00'), 'Al-Jaza\x92ir/Algérie', 'Republic', 'Abdelaziz Bouteflika', 35, 'DZ'),
 ('AGO', 'Angola', 'Africa', 'Central Africa', 1246700.0, 1975, 12878000, 38.3, Decimal('6648.00'), Decimal('7984.00'), 'Angola', 'Republic', 'José Eduardo dos Santos', 56, 'AO'),
 ('BEN', 'Benin', 'Africa', 'Western Africa', 112622.0, 1960, 6097000, 50.2, Decimal('2357.00'), Decimal('2141.00'), 'Bénin', 'Republic', 'Mathieu Kérékou', 187, 'BJ'),
 ('BWA', 'Botswana', 'Africa', 'Southern Africa', 581730.0, 1966, 1622000, 39.3, Decimal('4834.00'), Decimal('4935.00'), 'Botswana', 'Republic', 'Festus G. Mogae', 204, 'BW'),
 ('BFA', 'Burkina Faso', 'Africa', 'Western Africa', 274000.0, 1960, 11937000, 46.7, Decimal('2425.00'), Decimal('2201.00'), 'Burkina Faso', 'Republic', 'Blaise Compaoré', 549, 'BF'),
 ('BDI', 'Burundi', 'Africa', 'Eastern Africa', 27834.0, 1962, 6695000, 46.2, Decimal('903.00'), Decimal('982.00'), 'Burundi/Uburundi', 'Republic', 'Pierre Buyoya', 552, 'BI'),
 ('DJI', 'Djibouti', 'Africa', 'Eastern Africa', 23200.0, 1977, 638000, 50.8, Decimal('382.00'), Decimal('373.00'), 'Djibouti/Jibuti', 'Republic', 'Ismail Omar Guelleh', 585, 'DJ'),
 ('EGY', 'Egypt', 'Africa', 'Northern Africa', 1001450.0, 1922, 68470000, 63.3, Decimal('82710.00'), Decimal('75617.00'), 'Misr', 'Republic', 'Hosni Mubarak', 608, 'EG'),
 ('ERI', 'Eritrea', 'Africa', 'Eastern Africa', 117600.0, 1993, 3850000, 55.8, Decimal('650.00'), Decimal('755.00'), 'Ertra', 'Republic', 'Isayas Afewerki [Isaias Afwerki]', 652, 'ER'),
 ('ZAF', 'South Africa', 'Africa', 'Southern Africa', 1221040.0, 1910, 40377000, 51.1, Decimal('116729.00'), Decimal('129092.00'), 'South Africa', 'Republic', 'Thabo Mbeki', 716, 'ZA'),
 ('ETH', 'Ethiopia', 'Africa', 'Eastern Africa', 1104300.0, -1000, 62565000, 45.2, Decimal('6353.00'), Decimal('6180.00'), 'YeItyop´iya', 'Republic', 'Negasso Gidada', 756, 'ET'),
 ('GAB', 'Gabon', 'Africa', 'Central Africa', 267668.0, 1960, 1226000, 50.1, Decimal('5493.00'), Decimal('5279.00'), 'Le Gabon', 'Republic', 'Omar Bongo', 902, 'GA'),
 ('GMB', 'Gambia', 'Africa', 'Western Africa', 11295.0, 1965, 1305000, 53.2, Decimal('320.00'), Decimal('325.00'), 'The Gambia', 'Republic', 'Yahya Jammeh', 904, 'GM'),
 ('GHA', 'Ghana', 'Africa', 'Western Africa', 238533.0, 1957, 20212000, 57.4, Decimal('7137.00'), Decimal('6884.00'), 'Ghana', 'Republic', 'John Kufuor', 910, 'GH'),
 ('GIN', 'Guinea', 'Africa', 'Western Africa', 245857.0, 1958, 7430000, 45.6, Decimal('2352.00'), Decimal('2383.00'), 'Guinée', 'Republic', 'Lansana Conté', 926, 'GN'),
 ('GNB', 'Guinea-Bissau', 'Africa', 'Western Africa', 36125.0, 1974, 1213000, 49.0, Decimal('293.00'), Decimal('272.00'), 'Guiné-Bissau', 'Republic', 'Kumba Ialá', 927, 'GW'),
 ('CMR', 'Cameroon', 'Africa', 'Central Africa', 475442.0, 1960, 15085000, 54.8, Decimal('9174.00'), Decimal('8596.00'), 'Cameroun/Cameroon', 'Republic', 'Paul Biya', 1804, 'CM'),
 ('CPV', 'Cape Verde', 'Africa', 'Western Africa', 4033.0, 1975, 428000, 68.9, Decimal('435.00'), Decimal('420.00'), 'Cabo Verde', 'Republic', 'António Mascarenhas Monteiro', 1859, 'CV'),
 ('KEN', 'Kenya', 'Africa', 'Eastern Africa', 580367.0, 1963, 30080000, 48.0, Decimal('9217.00'), Decimal('10241.00'), 'Kenya', 'Republic', 'Daniel arap Moi', 1881, 'KE'),
 ('CAF', 'Central African Republic', 'Africa', 'Central Africa', 622984.0, 1960, 3615000, 44.0, Decimal('1054.00'), Decimal('993.00'), 'Centrafrique/Bê-Afrîka', 'Republic', 'Ange-Félix Patassé', 1889, 'CF'),
 ('COM', 'Comoros', 'Africa', 'Eastern Africa', 1862.0, 1975, 578000, 60.0, Decimal('4401.00'), Decimal('4361.00'), 'Komori/Comores', 'Republic', 'Azali Assoumani', 2295, 'KM'),
 ('COG', 'Congo', 'Africa', 'Central Africa', 342000.0, 1960, 2943000, 47.4, Decimal('2108.00'), Decimal('2287.00'), 'Congo', 'Republic', 'Denis Sassou-Nguesso', 2296, 'CG'),
 ('COD', 'Congo, The Democratic Republic of the', 'Africa', 'Central Africa', 2344860.0, 1960, 51654000, 48.8, Decimal('6964.00'), Decimal('2474.00'), 'République Démocratique du Congo', 'Republic', 'Joseph Kabila', 2298, 'CD'),
 ('LSO', 'Lesotho', 'Africa', 'Southern Africa', 30355.0, 1966, 2153000, 50.8, Decimal('1061.00'), Decimal('1161.00'), 'Lesotho', 'Constitutional Monarchy', 'Letsie III', 2437, 'LS'),
 ('LBR', 'Liberia', 'Africa', 'Western Africa', 111369.0, 1847, 3154000, 51.0, Decimal('2012.00'), None, 'Liberia', 'Republic', 'Charles Taylor', 2440, 'LR'),
 ('LBY', 'Libyan Arab Jamahiriya', 'Africa', 'Northern Africa', 1759540.0, 1951, 5605000, 75.5, Decimal('44806.00'), Decimal('40562.00'), 'Libiya', 'Socialistic State', 'Muammar al-Qadhafi', 2441, 'LY'),
 ('ESH', 'Western Sahara', 'Africa', 'Northern Africa', 266000.0, None, 293000, 49.8, Decimal('60.00'), None, 'As-Sahrawiya', 'Occupied by Marocco', 'Mohammed Abdel Aziz', 2453, 'EH'),
 ('MDG', 'Madagascar', 'Africa', 'Eastern Africa', 587041.0, 1960, 15942000, 55.0, Decimal('3750.00'), Decimal('3545.00'), 'Madagasikara/Madagascar', 'Federal Republic', 'Didier Ratsiraka', 2455, 'MG'),
 ('MWI', 'Malawi', 'Africa', 'Eastern Africa', 118484.0, 1964, 10925000, 37.6, Decimal('1687.00'), Decimal('2527.00'), 'Malawi', 'Republic', 'Bakili Muluzi', 2462, 'MW'),
 ('MLI', 'Mali', 'Africa', 'Western Africa', 1240190.0, 1960, 11234000, 46.7, Decimal('2642.00'), Decimal('2453.00'), 'Mali', 'Republic', 'Alpha Oumar Konaré', 2482, 'ML'),
 ('MAR', 'Morocco', 'Africa', 'Northern Africa', 446550.0, 1956, 28351000, 69.1, Decimal('36124.00'), Decimal('33514.00'), 'Al-Maghrib', 'Constitutional Monarchy', 'Mohammed VI', 2486, 'MA'),
 ('MRT', 'Mauritania', 'Africa', 'Western Africa', 1025520.0, 1960, 2670000, 50.8, Decimal('998.00'), Decimal('1081.00'), 'Muritaniya/Mauritanie', 'Republic', 'Maaouiya Ould Sid´Ahmad Taya', 2509, 'MR'),
 ('MUS', 'Mauritius', 'Africa', 'Eastern Africa', 2040.0, 1968, 1158000, 71.0, Decimal('4251.00'), Decimal('4186.00'), 'Mauritius', 'Republic', 'Cassam Uteem', 2511, 'MU'),
 ('MYT', 'Mayotte', 'Africa', 'Eastern Africa', 373.0, None, 149000, 59.5, Decimal('0.00'), None, 'Mayotte', 'Territorial Collectivity of France', 'Jacques Chirac', 2514, 'YT'),
 ('MOZ', 'Mozambique', 'Africa', 'Eastern Africa', 801590.0, 1975, 19680000, 37.5, Decimal('2891.00'), Decimal('2711.00'), 'Moçambique', 'Republic', 'Joaquím A. Chissano', 2698, 'MZ'),
 ('NAM', 'Namibia', 'Africa', 'Southern Africa', 824292.0, 1990, 1726000, 42.5, Decimal('3101.00'), Decimal('3384.00'), 'Namibia', 'Republic', 'Sam Nujoma', 2726, 'NA'),
 ('NER', 'Niger', 'Africa', 'Western Africa', 1267000.0, 1960, 10730000, 41.3, Decimal('1706.00'), Decimal('1580.00'), 'Niger', 'Republic', 'Mamadou Tandja', 2738, 'NE'),
 ('NGA', 'Nigeria', 'Africa', 'Western Africa', 923768.0, 1960, 111506000, 51.6, Decimal('65707.00'), Decimal('58623.00'), 'Nigeria', 'Federal Republic', 'Olusegun Obasanjo', 2754, 'NG'),
 ('CIV', 'Côte d\x92Ivoire', 'Africa', 'Western Africa', 322463.0, 1960, 14786000, 45.2, Decimal('11345.00'), Decimal('10285.00'), 'Côte d\x92Ivoire', 'Republic', 'Laurent Gbagbo', 2814, 'CI'),
 ('GNQ', 'Equatorial Guinea', 'Africa', 'Central Africa', 28051.0, 1968, 453000, 53.6, Decimal('283.00'), Decimal('542.00'), 'Guinea Ecuatorial', 'Republic', 'Teodoro Obiang Nguema Mbasogo', 2972, 'GQ'),
 ('REU', 'Réunion', 'Africa', 'Eastern Africa', 2510.0, None, 699000, 72.7, Decimal('8287.00'), Decimal('7988.00'), 'Réunion', 'Overseas Department of France', 'Jacques Chirac', 3017, 'RE'),
 ('RWA', 'Rwanda', 'Africa', 'Eastern Africa', 26338.0, 1962, 7733000, 39.3, Decimal('2036.00'), Decimal('1863.00'), 'Rwanda/Urwanda', 'Republic', 'Paul Kagame', 3047, 'RW'),
 ('SHN', 'Saint Helena', 'Africa', 'Western Africa', 314.0, None, 6000, 76.8, Decimal('0.00'), None, 'Saint Helena', 'Dependent Territory of the UK', 'Elisabeth II', 3063, 'SH'),
 ('ZMB', 'Zambia', 'Africa', 'Eastern Africa', 752618.0, 1964, 9169000, 37.2, Decimal('3377.00'), Decimal('3922.00'), 'Zambia', 'Republic', 'Frederick Chiluba', 3162, 'ZM'),
 ('STP', 'Sao Tome and Principe', 'Africa', 'Central Africa', 964.0, 1975, 147000, 65.3, Decimal('6.00'), None, 'São Tomé e Príncipe', 'Republic', 'Miguel Trovoada', 3172, 'ST'),
 ('SEN', 'Senegal', 'Africa', 'Western Africa', 196722.0, 1960, 9481000, 62.2, Decimal('4787.00'), Decimal('4542.00'), 'Sénégal/Sounougal', 'Republic', 'Abdoulaye Wade', 3198, 'SN'),
 ('SYC', 'Seychelles', 'Africa', 'Eastern Africa', 455.0, 1976, 77000, 70.4, Decimal('536.00'), Decimal('539.00'), 'Sesel/Seychelles', 'Republic', 'France-Albert René', 3206, 'SC'),
 ('SLE', 'Sierra Leone', 'Africa', 'Western Africa', 71740.0, 1961, 4854000, 45.3, Decimal('746.00'), Decimal('858.00'), 'Sierra Leone', 'Republic', 'Ahmed Tejan Kabbah', 3207, 'SL'),
 ('SOM', 'Somalia', 'Africa', 'Eastern Africa', 637657.0, 1960, 10097000, 46.2, Decimal('935.00'), None, 'Soomaaliya', 'Republic', 'Abdiqassim Salad Hassan', 3214, 'SO'),
 ('SDN', 'Sudan', 'Africa', 'Northern Africa', 2505810.0, 1956, 29490000, 56.6, Decimal('10162.00'), None, 'As-Sudan', 'Islamic Republic', 'Omar Hassan Ahmad al-Bashir', 3225, 'SD'),
 ('SWZ', 'Swaziland', 'Africa', 'Southern Africa', 17364.0, 1968, 1008000, 40.4, Decimal('1206.00'), Decimal('1312.00'), 'kaNgwane', 'Monarchy', 'Mswati III', 3244, 'SZ'),
 ('TZA', 'Tanzania', 'Africa', 'Eastern Africa', 883749.0, 1961, 33517000, 52.3, Decimal('8005.00'), Decimal('7388.00'), 'Tanzania', 'Republic', 'Benjamin William Mkapa', 3306, 'TZ'),
 ('TGO', 'Togo', 'Africa', 'Western Africa', 56785.0, 1960, 4629000, 54.7, Decimal('1449.00'), Decimal('1400.00'), 'Togo', 'Republic', 'Gnassingbé Eyadéma', 3332, 'TG'),
 ('TCD', 'Chad', 'Africa', 'Central Africa', 1284000.0, 1960, 7651000, 50.5, Decimal('1208.00'), Decimal('1102.00'), 'Tchad/Tshad', 'Republic', 'Idriss Déby', 3337, 'TD'),
 ('TUN', 'Tunisia', 'Africa', 'Northern Africa', 163610.0, 1956, 9586000, 73.7, Decimal('20026.00'), Decimal('18898.00'), 'Tunis/Tunisie', 'Republic', 'Zine al-Abidine Ben Ali', 3349, 'TN'),
 ('UGA', 'Uganda', 'Africa', 'Eastern Africa', 241038.0, 1962, 21778000, 42.9, Decimal('6313.00'), Decimal('6887.00'), 'Uganda', 'Republic', 'Yoweri Museveni', 3425, 'UG'),
 ('ZWE', 'Zimbabwe', 'Africa', 'Eastern Africa', 390757.0, 1980, 11669000, 37.8, Decimal('5951.00'), Decimal('8670.00'), 'Zimbabwe', 'Republic', 'Robert G. Mugabe', 4068, 'ZW'),
 ('IOT', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa', 78.0, None, 0, 0.0, Decimal('0.00'), None, 'British Indian Ocean Territory', 'Dependent Territory of the UK', 'Elisabeth II', None, 'IO')]

### List all data about all countries in the Middle East region

In [6]:
country.query("region == 'Middle East'").head(10)

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
10,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
12,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotarjan,126.0,AM
15,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144.0,AZ
17,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149.0,BH
55,GEO,Georgia,Asia,Middle East,69700.0,1991.0,4968000,64.5,6064.0,5924.0,Sakartvelo,Republic,Eduard evardnadze,905.0,GE
72,IRQ,Iraq,Asia,Middle East,438317.0,1932.0,23115000,66.5,11500.0,NaN,Al-´Iraq,Republic,Saddam Hussein al-Takriti,1365.0,IQ
76,ISR,Israel,Asia,Middle East,21056.0,1948.0,6217000,78.6,97477.0,98577.0,Yisrael/Israil,Republic,Moshe Katzav,1450.0,IL
82,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
83,JOR,Jordan,Asia,Middle East,88946.0,1946.0,5083000,77.4,7526.0,7051.0,Al-Urdunn,Constitutional Monarchy,Abdullah II,1786.0,JO
106,KWT,Kuwait,Asia,Middle East,17818.0,1961.0,1972000,76.1,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW

###  List only the country name and region for the countries in the Middle East region

In [7]:
country.query("region == 'Middle East'").project(['name','region'])

                     name       region
10   United Arab Emirates  Middle East
12                Armenia  Middle East
15             Azerbaijan  Middle East
17                Bahrain  Middle East
55                Georgia  Middle East
72                   Iraq  Middle East
76                 Israel  Middle East
82                  Yemen  Middle East
83                 Jordan  Middle East
106                Kuwait  Middle East
107                Cyprus  Middle East
111               Lebanon  Middle East
150                  Oman  Middle East
163                 Qatar  Middle East
182          Saudi Arabia  Middle East
196                 Syria  Middle East
209                Turkey  Middle East
231             Palestine  Middle East

### Show the country name and life expectancy of the 5 countries with the longest life expectancy

In [8]:
country.project(['name', 'lifeexpectancy']).sort(['lifeexpectancy'],ascending=False).head(5)

           name  lifeexpectancy
6       Andorra            83.5
118       Macao            81.6
180  San Marino            81.1
81        Japan            80.7
186   Singapore            80.1

### Show the country name, population, and gnp of the 5 countries with the smallest gnp

In [9]:
country.project(['name','population','gnp']).sort(['gnp']).head(5)

                                     name  population  gnp
238  United States Minor Outlying Islands           0  0.0
49                       Falkland Islands        2000  0.0
52                          Faroe Islands       43000  0.0
59                              Greenland       56000  0.0
171                          Saint Helena        6000  0.0

Alternatively if we want to see countries with non-zero gnp we can do:

In [10]:
country.query("gnp > 0").project(['name','population','gnp']).sort(['gnp']).head(5)

                              name  population   gnp
181          Sao Tome and Principe      147000   6.0
212                         Tuvalu       12000   6.0
223  Holy See (Vatican City State)        1000   9.0
95                        Kiribati       83000  40.7
117                 Western Sahara      293000  60.0

### Show all of the distinct forms of government

In [11]:
# because relations can not have duplicate rows, a project automatically removes all duplicates
country.project(['governmentform'])

                                   governmentform
0                                 Islamic Emirate
1                         Constitutional Monarchy
2    Nonmetropolitan Territory of The Netherlands
3                                        Republic
5                                    US Territory
6                    Parliamentary Coprincipality
8                   Dependent Territory of the UK
10                             Emirate Federation
11                               Federal Republic
14            Constitutional Monarchy, Federation
17                             Monarchy (Emirate)
24                                       Monarchy
31                           Monarchy (Sultanate)
37       Nonmetropolitan Territory of New Zealand
52                                Part of Denmark
60                  Overseas Department of France
68         Special Administrative Region of China
69                  Dependent Territory of Norway
73                               Islamic Republic
78                        Administrated by the UN
84                         Territory of Australia
93                               People'sRepublic
101                          Socialistic Republic
106             Constitutional Monarchy (Emirate)
113                             Socialistic State
117                           Occupied by Marocco
131            Territorial Collectivity of France
158                        Commonwealth of the US
166           Nonmetropolitan Territory of France
179                         Parlementary Monarchy
195                                    Federation
223                      Independent Church State
231                               Autonomous Area
232                              Co-administrated
238                 Dependent Territory of the US

### Show all of the distinct regions of the world

In [12]:
country.project(['region'])

                        region
0    Southern and Central Asia
1               Western Europe
2                    Caribbean
3              Southern Europe
4              Northern Africa
5                    Polynesia
7               Central Africa
10                 Middle East
11               South America
14   Australia and New Zealand
21             Central America
22              Western Africa
23               North America
27             Southern Africa
29             British Islands
31              Southeast Asia
32              Eastern Europe
34              Eastern Africa
50                   Melanesia
52            Nordic Countries
61                  Micronesia
68                Eastern Asia
109           Baltic Countries
232                 Antarctica
238       Micronesia/Caribbean

### List the country name and gnp of all of the countries that are Monarchies

In [13]:
country.query("governmentform == 'Monarchy'").project(['name','gnp'])

             name       gnp
24         Bhutan     372.0
163         Qatar    9472.0
182  Saudi Arabia  137635.0
194     Swaziland    1206.0
204         Tonga     146.0

### List the country name, governmentform and population of the countries that are any kind of Monarchy (Monarchy, Constitutional Monarchy, or Monarchy (Sultanate)

In [14]:
country.query("governmentform == 'Monarchy' | governmentform == 'Constitutional Monarchy' | governmentform == 'Monarchy (Emirate)' | governmentform == 'Monarchy (Sultanate)'").project(['name','gnp'])

                                 name        gnp
1                         Netherlands   371362.0
9                 Antigua and Barbuda      612.0
16                            Bahamas     3527.0
17                            Bahrain     6366.0
19                           Barbados     2223.0
21                             Belize      630.0
24                             Bhutan      372.0
29                     United Kingdom  1378330.0
31                             Brunei    11705.0
46                              Spain   553233.0
58                            Grenada      318.0
80                            Jamaica     6871.0
81                              Japan  3787042.0
83                             Jordan     7526.0
86                           Cambodia     5121.0
110                           Lesotho     1061.0
114                     Liechtenstein     1119.0
116                        Luxembourg    16321.0
126                           Morocco    36124.0
135                            Monaco      776.0
142                             Nepal     4768.0
148                            Norway   145895.0
150                              Oman    16904.0
154                  Papua New Guinea     4988.0
163                             Qatar     9472.0
170                            Sweden   226492.0
172             Saint Kitts and Nevis      299.0
173                       Saint Lucia      571.0
174  Saint Vincent and the Grenadines      285.0
177                   Solomon Islands      182.0
182                      Saudi Arabia   137635.0
194                         Swaziland     1206.0
200                           Denmark   174099.0
201                          Thailand   116416.0
204                             Tonga      146.0
212                            Tuvalu        6.0
218                       New Zealand    54669.0

### List the country name and gnp of the countries in Southeast Asia with population less than 5 million

In [15]:
country.query("population < 5000000 & region == 'Southeast Asia'").project(['name','gnp'])

           name      gnp
31       Brunei  11705.0
78   East Timor      0.0
186   Singapore  86503.0

### List the country names, gnp, and population where the new gnp is more than the old gnp

In [16]:
country.query("gnp > gnpold").project(['name','gnp'])

                        name        gnp
1                Netherlands   371362.0
3                    Albania     3205.0
4                    Algeria    49982.0
9        Antigua and Barbuda      612.0
10      United Arab Emirates    37966.0
11                 Argentina   340238.0
12                   Armenia     1813.0
13                     Aruba      828.0
15                Azerbaijan     4127.0
16                   Bahamas     3527.0
17                   Bahrain     6366.0
18                Bangladesh    32852.0
19                  Barbados     2223.0
20                   Belgium   249704.0
21                    Belize      630.0
22                     Benin     2357.0
23                   Bermuda     2328.0
25                   Bolivia     8571.0
29            United Kingdom  1378330.0
30   Virgin Islands, British      612.0
32                  Bulgaria    12178.0
33              Burkina Faso     2425.0
35            Cayman Islands     1263.0
38                Costa Rica    10226.0
39                  Djibouti      382.0
40                  Dominica      256.0
41        Dominican Republic    15846.0
42                   Ecuador    19770.0
43                     Egypt    82710.0
44               El Salvador    11863.0
..                       ...        ...
164                   France  1424285.0
166         French Polynesia      818.0
167                  Réunion     8287.0
168                  Romania    38158.0
169                   Rwanda     2036.0
176                  Germany  2133367.0
183                  Senegal     4787.0
187                 Slovakia    20594.0
188                 Slovenia    19756.0
190                Sri Lanka    15706.0
192                  Finland   121914.0
193                 Suriname      870.0
195              Switzerland   264478.0
196                    Syria    65984.0
197               Tajikistan     1990.0
199                 Tanzania     8005.0
200                  Denmark   174099.0
202                     Togo     1449.0
205      Trinidad and Tobago     6232.0
206                     Chad     1208.0
207           Czech Republic    55017.0
208                  Tunisia    20026.0
209                   Turkey   210721.0
210             Turkmenistan     4397.0
215                  Hungary    48267.0
216                  Uruguay    20831.0
222                  Vanuatu      261.0
224                Venezuela    95023.0
227                  Estonia     5328.0
228            United States  8510700.0

[115 rows x 2 columns]